steps:
- name: gcr.io/cloud-builders/wget
  args: ['-O', 'caddy', 'https://github.com/caddyserver/caddy/releases/download/v2.0.0-beta.15/caddy2_beta15_linux_amd64']
  id: CADDY
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-o', 'ogp-app']
  env: ['CGO_ENABLED=0']
  waitFor:
  id: OGPAPP_BUILD

- name: 'gcr.io/cloud-builders/docker'
  waitFor:
  - 'CADDY'
  - 'OGPAPP_BUILD'

images:
  ['gcr.io/$PROJECT_ID/ogp-app']