steps:
- name: 'gcr.io/cloud-builders/go:debian'
  env:
  - 'GO111MODULE=on'
  - 'CGO_ENABLED=0'
  - 'PROJECT_ROOT=ogp-app'
  args: ['build', '-o', 'ogp-app', '.']
  waitFor: ['-']
  id: OGPAPP

- name: 'node:13.10.1-stretch-slim'
  args: ['npm', 'ci', '&&', 'npm', 'run', 'build']
  dir: 'client'
  id: CLIENT

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/ogp-app', '.']
  waitFor:
  - 'OGPAPP'
  - 'CLIENT'

images:
- 'gcr.io/$PROJECT_ID/ogp-app'