steps:
# TODO(ymotongpoo): Remove this `chown` part once the issue on Cloud Bulid gets fixed
- name: 'alpine'
  args: ['chown', 'root:root', '-R', '.']
  waitFor: ['-']
  id: CHOWN

- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'NODE_VERSION=13.10.1'
  - 'PYTHON=python2.7'
  args: ['ci']
  dir: 'client'
  id: 'CLIENT_CI'

- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'NODE_VERSION=13.10.1'
  args: ['run', 'build']
  dir: 'client'
  waitFor:
  - 'CLIENT_CI'
  id: 'CLIENT_BUILD'

- name: 'gcr.io/cloud-builders/bazel'
  args: ['run',
         '--google_default_credentials',
         '--spawn_strategy=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=Genrule=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=ContainerPushDigest=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=TemplateExpand=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=SourceSymlinkManifest=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=SymlinkTree=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--strategy=Middleman=local,processwrapper-sandbox,sandboxed,standalone,worker',
         '--remote_http_cache=https://storage.googleapis.com/ogp-app-build',
         ':ogpapp_push']
  waitFor:
  - 'CLIENT_BUILD'
  - 'CHOWN'
  id: 'CONTAINER_PUSH'

options:
  machineType: 'N1_HIGHCPU_8'