steps:
# TODO(ymotongpoo): Remove this `chown` part once the issue on Cloud Bulid gets fixed
- name: 'alpine'
  args: ['chown', 'root:root', 'Koruri-Bold.ttf']
  waitFor: ['-']
  id: CHOWN_TTF
- name: 'alpine'
  args: ['chown', 'root:root', '-R', 'config']
  waitFor: ['-']
  id: CHOWN_CONFIG

- name: 'gcr.io/cloud-builders/go:debian'
  env:
  - 'GO111MODULE=on'
  - 'CGO_ENABLED=0'
  - 'PROJECT_ROOT=ogp-app'
  args: ['build', '-o', 'ogp-app', '.']
  waitFor: ['-']
  id: 'OGPAPP'

- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'NODE_VERSION=13.10.1'
  - 'PYTHON=python2.7'
  args: ['ci']
  dir: 'client'
  id: 'CLIENT_CI'

- name: 'gcr.io/cloud-builders/npm'
  env:
  - 'NODE_VERSION=13.10.1'
  args: ['run', 'build']
  dir: 'client'
  waitFor:
  - 'CLIENT_CI'
  id: 'CLIENT_BUILD'

- name: 'gcr.io/cloud-builders/bazel'
  args: ['run', '--host_force_python=PY2', ':ogpapp_push']
  waitFor:
  - 'OGPAPP'
  - 'CLIENT_BUILD'
  - 'CHOWN_TTF'
  - 'CHOWN_CONFIG'
  id: 'CONTAINER_PUSH'

options:
  machineType: 'N1_HIGHCPU_8'